feat(solidjs): Add API response to gists view
thisdot/starter.dev-github-showcases pull request #1006
Opened 2022-11-30 10:36 UTC by SDaian

## Acceptance Criteria

- [ ]  Add the current API response from Backend to the frontend

2022-11-30 17:35 UTC, danecando requested changes

2022-11-30 17:35 UTC, danecando commented on solidjs-tailwind/src/pages/Home.jsx
> +        <UserGists gists={userGists} />
```suggestion
        <UserGists gists={userGists()} />
```

Works for me when I call userGists as a function

2022-12-01 13:43 UTC, danecando approved these changes

2022-12-02 00:16 UTC, AllStackDev1 approved these changes

2022-12-02 08:31 UTC, merged