feat(solidjs): Add test for helpers
thisdot/starter.dev-github-showcases pull request #1026
Opened 2022-12-02 15:23 UTC by SDaian

## Acceptance Criteria

- [x] Add test on helpers used inside the project.

Closes: #1002

2022-12-08 12:10 UTC, SDaian commented on solidjs-tailwind/src/helper/getLanguages.spec.js
> +const MOCK_REPOS = [
extracted to a shared mock file, thanks @mbicknese

2022-12-16 15:29 UTC, vyktoremario commented on solidjs-tailwind/src/helper/getLanguages.js
> +  console.log(repos);
I am guessing this for debugging purposes?

2022-12-16 15:29 UTC, vyktoremario requested changes
Left a comment

2022-12-16 23:47 UTC, vyktoremario approved these changes

2022-12-19 11:51 UTC, merged