feat: adds orgs and starred repos to schema
thisdot/starter.dev-github-showcases pull request #1031
Opened 2022-12-06 00:04 UTC by WillHutt

2022-12-16 21:01 UTC, danecando approved these changes
Wondering if the graphql.ts file is generated and if so do we want to check it in to source control? Everything LGTM to me though

2023-02-13 17:21 UTC, Amdrel requested changes
Although there's no tests in this PR and it is required by the guidelines, it does not appear that this subproject has any testing infrastructure set up yet. I think it would be outside of the scope of this PR to set that all up and that can be handled in a future ticket. Other than that I see no glaring issues of note.

The comments that were left are mainly nitpicks that should be easily resolvable.

2023-02-13 17:21 UTC, Amdrel commented on angular-apollo-tailwind/src/main.ts
>    .catch((err) => console.error(err));
Nitpick: Removing unrelated and likely unintended whitespace change.

```suggestion
platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.error(err));

```

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/src/datasources/github-api.ts
> +// import { repoFormatter, orgFormatter, ownerFormatter } from 'src/formatters';
Blocker: Let's add a ticket number to the ticket being referenced here.

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/src/datasources/github-api.ts
> +    // return orgFormatter(data);
Suggestion: Either remove unused and commented out code or reference a ticket number if related to the aforementioned formatting and testing ticket.

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/src/datasources/github-api.ts
> +    // return ownerFormatter(data);
Suggestion: Either remove unused and commented out code or reference a ticket number if related to the aforementioned formatting and testing ticket.

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/src/datasources/github-api.ts
> +    // return repoFormatter(data);
Suggestion: Either remove unused and commented out code or reference a ticket number if related to the aforementioned formatting and testing ticket.

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/src/datasources/github-api.ts
> +    // return repoFormatter(data);
Suggestion: Either remove unused and commented out code or reference a ticket number if related to the aforementioned formatting and testing ticket.

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/src/schema/github/github.typedefs.ts
>    """
Suggestion: Update comment to reflect schema change.

```suggestion
  """
  A User object used in Repo
  """
```

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/src/schema/github/github.typedefs.ts
>    """
Suggestion: Update comment to reflect schema change.

```suggestion
  """
  An Owner object
  """
```

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/src/schema/github/github.typedefs.ts
> +  A Organization object used in Owner
Suggestion: Grammar 😛

```suggestion
  An Organization object used in Owner
```

2023-02-13 17:21 UTC, Amdrel commented on starter-dev-backend/types/graphql.ts
> +/** A Owner object used in Repo */
Suggestion: Grammar 😛

```suggestion
/** An Owner object used in Repo */
```

2023-02-13 23:34 UTC, morgnism approved these changes
LGTM

2023-02-13 23:39 UTC, Amdrel approved these changes

2023-02-14 00:30 UTC, merged