feat(qwik-pod): Create test minor components
thisdot/starter.dev-github-showcases pull request #1069
Opened 2022-12-15 13:29 UTC by SDaian

## Description

- [x] Creation of test for minor components

Closes: #1041

2022-12-20 18:16 UTC, AllStackDev1 approved these changes
![image](https://user-images.githubusercontent.com/36667083/208737239-844d19c4-790d-4f1a-a52b-7bee44c892ce.png)
So i get this errors...

2022-12-20 18:19 UTC, AllStackDev1 requested changes
Run test again some test are failing

2023-01-04 08:15 UTC, iamjerryhogan requested changes
over five test failed please review.

2023-01-04 08:15 UTC, iamjerryhogan commented on qwik-graphql-tailwind/src/components/repo-tree/repo-tree.spec.tsx
> +    console.log(screen.outerHTML);
Please remove, and it seems this test isn't completed

2023-01-04 08:15 UTC, iamjerryhogan commented on qwik-graphql-tailwind/src/components/user-dropdown/user-dropdown.spec.tsx
> +    console.log(screen.outerHTML);
please remove and complete test

2023-01-12 20:18 UTC, markshenouda approved these changes
Good job
![image](https://user-images.githubusercontent.com/49324987/212171826-f1f47a21-483f-4222-af00-b523858944bd.png)

2023-01-13 00:02 UTC, merged