fix: Update README to include details about reason deployment to Netl…
thisdot/starter.dev-github-showcases pull request #1101
Opened 2022-12-16 18:45 UTC by markshenouda

…ify is broken

2022-12-16 20:49 UTC, danecando approved these changes

2022-12-16 20:49 UTC, danecando commented on qwik-graphql-tailwind/README.md
> +> ## Declaimer ⚠️
```suggestion
> ## Disclaimer ⚠️
```

2023-01-04 08:16 UTC, iamjerryhogan approved these changes

2023-01-04 08:19 UTC, iamjerryhogan commented on qwik-graphql-tailwind/README.md
> +> ## Declaimer ⚠️
Disclaimer

2023-01-04 08:19 UTC, iamjerryhogan requested changes
seems there is a minor change with a typo

2023-01-06 08:16 UTC, AllStackDev1 approved these changes

2023-01-06 10:56 UTC, AllStackDev1 approved these changes

2023-01-06 10:57 UTC, merged