fix: pagination in profile page
thisdot/starter.dev-github-showcases pull request #1234
Opened 2023-01-12 11:20 UTC by Megio

Step to reproduce:

- go to the profile page
- click the next button at the bottom of the repo list

Now pagination should work.
Fixes: #1219 

NB: we still have the "Prev" button problem, but it seems a problem related to GitHub API response (everytime we click the Prev button the API response return pageInfo with wrong values)

2023-01-12 12:00 UTC, hdJerry requested changes

2023-01-12 12:00 UTC, hdJerry commented on qwik-graphql-tailwind/src/components/user-repos/user-repos.tsx
Please, lets first reverse to what was there before.
the filter and sort were all working. But now they are not

2023-01-12 12:00 UTC, hdJerry commented on qwik-graphql-tailwind/src/components/user-repos/user-repos.tsx
![Screenshot 2023-01-12 at 12 59 04](https://user-images.githubusercontent.com/28502531/212061203-80ac54a8-6e54-4b9c-b3ce-3e37f3a50b97.jpg)

Another example...

2023-01-12 20:26 UTC, markshenouda submitted a review, later dismissed
Looks fantastic 🔥

2023-01-13 02:17 UTC, AllStackDev1 approved these changes

2023-01-13 11:16 UTC, hdJerry requested changes
The filter isn't still working

![Screenshot 2023-01-13 at 12 18 00](https://user-images.githubusercontent.com/28502531/212315040-81cfe7a0-b9c6-4480-b776-9d8410fcf25d.jpg)

2023-01-13 14:29 UTC, hdJerry approved these changes
Thanks captain

2023-01-13 14:30 UTC, merged