Create navigation header
thisdot/starter.dev-github-showcases pull request #1385
Opened 2023-02-06 16:13 UTC by AllStackDev1

Closes: #1362
# Create navigation header

## Background

As a user, I should see a header with the GitHub logo as a home button on the left, and my user profile picture on the right attached to a dropdown menu. The menu should show links for navigating to my profile and a sign out link.

## Acceptance

- [x] Top nav
  - [x] GitHub logo on the left
  - [x] User avatar with dropdown on the right
  - [x] Navigation to profile in the dropdown (can point to not yet existing page)
  - [x] Logout link in the dropdown (can point to not yet existing functionality yet)
- [x] Placeholder for main content

## Notes

2023-02-07 08:58 UTC, hdJerry requested changes

2023-02-07 08:58 UTC, hdJerry commented on solidstart-tanstackquery-tailwind-modules/src/components/UserDropdown/UserDropdown.tsx
> +  const signOut = () => {
I believe there is a ticket for sign-out functionality. This shouldn't have been implemented yet

2023-02-07 08:58 UTC, hdJerry commented on solidstart-tanstackquery-tailwind-modules/src/components/UserDropdown/UserDropdown.tsx
> +            {props.username && (
make use of `switch and match` or `show` for solidjs here. We need to be more solidjs than react

2023-02-07 17:28 UTC, Megio commented on solidstart-tanstackquery-tailwind-modules/src/utils/onclickOutside.ts
> +};
At least we can typed the el and e, never see accessor, don't know what type it is :-D

```suggestion
export const clickOutside = (el: HTMLDivElement, accessor: any) => {
  const onClick = (e: MouseEvent) => {
    !el.contains(e.target as unknown as HTMLDivElement) && accessor()?.();
  };
  document.body.addEventListener('click', onClick);

  onCleanup(() => document.body.removeEventListener('click', onClick));
};
```

2023-02-08 09:07 UTC, hdJerry requested changes

2023-02-08 09:07 UTC, hdJerry commented on solidstart-tanstackquery-tailwind-modules/src/components/UserDropdown/UserDropdown.tsx
> +            {props.image && (
you forgot Show here 😀

2023-02-08 09:15 UTC, hdJerry approved these changes
Thanks sir

2023-02-08 09:18 UTC, merged