feat: single repo issues tab view
thisdot/starter.dev-github-showcases pull request #1469
Opened 2023-02-14 15:25 UTC by markshenouda

2023-02-14 16:10 UTC, SDaian requested changes

2023-02-14 16:10 UTC, SDaian commented on solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/issues.tsx
> +import { RepoAbout } from '~/components/RepoAbout';
it has some lint errors.. should we care about that?

2023-02-14 16:18 UTC, SDaian requested changes

2023-02-14 16:18 UTC, SDaian commented on solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/utils.tsx
> +export const parseSortParams = (options, value, position) =>
index.ts is empty, should we delete?

2023-02-14 18:04 UTC, Megio commented on solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesListItem/PRAndIssuesListItem.tsx
> +          )}
Also here we can use `<Show when=`

2023-02-14 18:04 UTC, Megio commented on solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/RepoIssues.tsx
> +            )}
here we can use `<Switch><Match when=` pattern

2023-02-14 18:04 UTC, Megio commented on solidstart-tanstackquery-tailwind-modules/src/components/Pagination/Pagination.tsx
> +      ) : null}
Also here we could use `<Show when=` pattern

2023-02-15 21:03 UTC, BigAB commented on solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesListItem/PRAndIssuesListItem.tsx
> +                )}
Seems like `<Switch>` and `<Match>` would be appropriate here

2023-02-20 09:58 UTC, Megio commented
Hi @markshenouda reviewing this PR I see that we have a lot of errors or warnings, I saw some `any` types and a `createResource` in `solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/RepoIssues.tsx` instead of a `createQuery`. Are you still working on it? If you need any kind of help let me know  🙂

2023-02-20 10:57 UTC, Megio submitted a review, later dismissed

2023-02-22 13:32 UTC, closed without merging