expo-feat: navigation header
thisdot/starter.dev-github-showcases pull request #1543
Opened 2023-03-02 14:57 UTC by Megio

Created Navigation Header Component.
Styles could be changed if needed, the profile picture is hardcoded waiting for real data, and sign-out function has not been implemented yet.

Fixes: #1528

2023-03-03 15:13 UTC, vyktoremario submitted a review, later dismissed

2023-03-03 23:59 UTC, BigAB requested changes
I would say this looks pretty good, but you need to run
```sh
yarn format
```
...and remove the `yarn-error.log` error from this PR.

You may want to look into configuring your editor to run `prettier` on save

2023-03-06 10:55 UTC, hdJerry requested changes
Also, there are some conflicts that you need to look over. Thanks

2023-03-06 10:55 UTC, hdJerry commented on expo-zustand-styled-components/src/components/Header/Header.tsx
> +      {/* <Link to="/"> */}
please remove comments as we aren't gonna use Link, yeah?

2023-03-07 18:08 UTC, BigAB submitted a review, later dismissed

2023-03-08 02:14 UTC, AllStackDev1 reviewed
This will help with the failing tests

https://react-native-async-storage.github.io/async-storage/docs/advanced/jest/

2023-03-08 09:11 UTC, AllStackDev1 submitted a review, later dismissed

2023-03-08 10:26 UTC, hdJerry requested changes

2023-03-08 10:26 UTC, hdJerry commented on expo-zustand-styled-components/src/screens/Home/Home.tsx
> +        {/* <Button title="Logout" onPress={() => logout()} /> */}
Please is there a need for this comment?

2023-03-08 10:30 UTC, hdJerry approved these changes
Thanks Sir

2023-03-08 10:32 UTC, AllStackDev1 approved these changes

2023-03-08 10:45 UTC, merged