Organization page layout with data integrations
thisdot/starter.dev-github-showcases pull request #1584
Opened 2023-03-10 21:34 UTC by AllStackDev1

Closes: #1536

Mobile:
![Simulator Screen Recording - iPhone 14 - 2023-03-10 at 22 15 53](https://user-images.githubusercontent.com/36667083/224431285-99d6ed38-285f-4fb8-a203-dd8e3668b533.gif)

Web:

# Setup organization page layout

## Background

As a user, I can view a page for any organiziation I have available, which will show that organization’s list of repositories. I can also see options to search my repositories, sort them, and filter them. (Functionality does not need to work yet for these options, they just need to be visible.)

## Acceptance

- [x] 1 column layout
- [x] sub-header spanning both columns, showing book icon and repositories title - should be sticky on scroll
- [x] Top of main section - search / filter / sort component
- [x] Main section - card for all org repos

## Notes

2023-03-13 11:06 UTC, hdJerry requested changes

2023-03-13 11:06 UTC, hdJerry commented on expo-zustand-styled-components/src/screens/Organization/Organization.styles.ts
> +  border-bottom-color: #e1e4e8;
I believe this color exists in the colors object, if it doesn't you can update it so we can reuse it where appropriate.

What do you think?

2023-03-14 13:03 UTC, hdJerry submitted a review, later dismissed

2023-03-15 14:39 UTC, Megio commented on expo-zustand-styled-components/src/components/FilterDropdown/DropdownOverlay.tsx
> +        },
I don't understand why we need to spread an object in this way

2023-03-15 14:39 UTC, Megio commented on expo-zustand-styled-components/src/components/FilterDropdown/DropdownOverlay.tsx
> +});
We are using styled component, can we "convert" this into a styled component?

2023-03-15 14:39 UTC, Megio commented on expo-zustand-styled-components/src/components/FilterDropdown/DropdownWindow.tsx
> +});
We are using styled component, can we "convert" these into some styled components?

2023-03-15 14:39 UTC, Megio commented on expo-zustand-styled-components/src/hooks/useLayoutDropdown.ts
> +      },
DOn't understand what we are spreading here

2023-03-16 10:29 UTC, hdJerry commented
What's the essence of the modal? it's just a dropdown. There has to be a better way than the modal. For mobile it's okay not for desktop.

Can you explain the decision?

2023-03-16 11:44 UTC, Megio approved these changes
LGTM

2023-03-16 12:09 UTC, merged