pagination add to org profile and user profile
thisdot/starter.dev-github-showcases pull request #1690
Opened 2023-03-28 03:05 UTC by AllStackDev1

Closes:  #1637

Added Pagination in orgs profile and user profile screen

2023-03-28 14:30 UTC, hdJerry requested changes
When I click next in the pagination for the issue tab, the dropdowns disappear, and then I click next again it appears.

Also, it will be better to clear the before and after in the URL params when changing from open to closed issue or pr as the pagination/and API call works with that as well to avoid issues.


![Screenshot 2023-03-28 at 15 24 44](https://user-images.githubusercontent.com/28502531/228271598-1488494e-7017-4a90-935a-e215fc4034e1.jpg)

2023-03-28 14:35 UTC, hdJerry requested changes
.

2023-03-28 14:35 UTC, hdJerry commented on expo-zustand-styled-components/src/components/Header/Header.tsx
> +const Header = ({ width }: { width: number }) => {
The changes in this file have nothing to do with pagination, or does it?

2023-03-28 14:35 UTC, hdJerry commented on expo-zustand-styled-components/src/components/IssuePullRequestCard/IssuePullRequestCard.tsx
> +
The changes in this file have nothing to do with pagination, why make the changes?

2023-03-29 09:08 UTC, hdJerry requested changes
- In the profile/org repo page, when I click next and then prev, the pagination button is disabled.
- When I click next like 2 times and click prev, it goes back to the first page.

All these happened in both org and profile repo page

2023-03-29 09:30 UTC, AllStackDev1 commented
> * In the profile/org repo page, when I click next and then prev, the pagination button is disabled.
> * When I click next like 2 times and click prev, it goes back to the first page.
> 
> All these happened in both org and profile repo page

All these are what we experience in other showcases, just that in this case we don't totally remove the pagination we simply disable them.

2023-03-29 09:31 UTC, hdJerry commented
> > * In the profile/org repo page, when I click next and then prev, the pagination button is disabled.
> > * When I click next like 2 times and click prev, it goes back to the first page.
> > 
> > All these happened in both org and profile repo page
> 
> All these are what we experience in other showcases, just that in this case we don't totally remove the pagination we simply disable them.

Thanks for letting us know sir.

2023-03-29 09:32 UTC, hdJerry approved these changes
Thanks.

2023-03-29 09:33 UTC, merged