expo-feat: added organization about and repositories tests
thisdot/starter.dev-github-showcases pull request #1760
Opened 2023-03-31 09:26 UTC by Megio

Added Organization Repo and About tests

Fixes: #1730

2023-03-31 10:12 UTC, vyktoremario commented on expo-zustand-styled-components/src/components/Organization/Repositories/Repositories.spec.tsx
Run prettier on this file.
Needs a new line.

2023-03-31 10:23 UTC, vyktoremario commented on expo-zustand-styled-components/src/components/Organization/Repositories/Repositories.spec.tsx
> +describe('User dropdown', () => {
You forgot to rename this🙂

2023-03-31 10:26 UTC, vyktoremario commented on expo-zustand-styled-components/src/components/Organization/Repositories/Repositories.spec.tsx
Also, is it possible to test fireEvents, since we have events that happen when you click something?

Since this is the Repository component, maybe you can just test if clicking on the repo name fires an event. 

Not necessary, but more of a suggestion.

2023-03-31 10:26 UTC, vyktoremario requested changes
Left some comments and a suggestion

2023-04-03 16:44 UTC, hdJerry approved these changes

2023-04-04 05:02 UTC, AllStackDev1 approved these changes

2023-04-04 05:04 UTC, merged