[WIP]feat: adds user gists
thisdot/starter.dev-github-showcases pull request #207
Opened 2022-03-10 00:59 UTC by WillHutt

2022-03-11 00:05 UTC, WillHutt commented
@AllanJeremy Do you have any incite to this issue I've run into?

2022-03-11 05:23 UTC, AllanJeremy commented
> @AllanJeremy Do you have any incite to this issue I've run into?

Just got to the computer, let me check it out

2022-03-11 05:26 UTC, AllanJeremy requested changes
One reason you are not seeing the data is because when we access `ref`s in components/views, we do not need to use `.value`. That means that the check for `gistLoading.value` will always return `false` since the value in the DOM is actually `undefined`.

Made a suggested change~

2022-03-11 05:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/composables/github/types/index.ts
> +import GistItem from './Gist';
We can shorten this to 

```ts
export { default as GistItem} from './Gist'
```

2022-03-11 05:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/components/GistsPanel/GistsPanel.vue
> +    <q-card-section v-if="!gistLoading.value">
```vue
<q-card-section v-if="!gistLoading">
   <!-- -->
</q-card-section>
```

2022-03-11 20:27 UTC, WillHutt commented
I resolved your comments, but that wasn't the issue. 

The issue stems from the `getUserGists` that has a watch to see when it updates the data. For some reason, the data won't update in the actual component.

2022-05-03 18:49 UTC, AllanJeremy commented on vue3-ts-quasar/src/composables/github/useGists.ts
> +import { parseQuery } from '@/components/GistsPanel/parseQuery';
Structurally, would recommend that we don't import dependencies from within components into composables.

Composables are meant to be reusable pieces of functionality within the application and thus adding them here would be coupling the composable to a GistsPanel dependency. This means if we wanted to use the get gists functionality with a different component/page, we'd need to pull the `parseQuery` functionality from the `GistsPanel` component.

## Suggestion
Migrate the `parseQuery` functionality into useGists. That way, it is self-contained.

2022-05-03 18:51 UTC, AllanJeremy commented on vue3-ts-quasar/src/composables/github/useGists.ts
> +  const getUserGists = (): any => {
Prefer strongly typing whenever possible. I think we should avoid the use of `any` whenever possible.

2022-05-03 19:32 UTC, AllanJeremy requested changes
Hey, great job so far! Functionally, it works perfect. 
However, got a few structural and type related issues that would need resolved.

Feel free to ping me incase of anything @WillHutt .

Cheers.

2022-05-03 19:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/components/GistsPanel/parseQuery.ts
> +export function parseQuery(data: UserGistsQuery): GistParse {
The return type for this is actually `GistItem[]`

2022-05-03 19:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/components/GistsPanel/parseQuery.ts
> +export function parseQuery(data: UserGistsQuery): GistParse {
```ts
function parseQuery(data: UserGistsQuery): GistItem[]
```
This will provide you with better type inference in the `GistsPanel` component

2022-05-03 19:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/components/GistsPanel/parseQuery.ts
> +type GistParse = {
With the changes below, `GistParse` type is no longer needed.

2022-05-03 19:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/composables/github/types/index.ts
> +export { default as GistItem } from './Gist';
Prefer named exports in types since that means we can have multiple related types in one file.
```ts
export * from './Gist';
```

2022-05-03 19:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/composables/github/types/Gist.ts
> +}
Prefer named exports in types since that means we can have multiple related types in one file.
```ts
export interface GistItem
```

2022-05-03 19:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/composables/github/useGists.ts
> +interface UseGists {
We can move all individual related types to `src/composables/github/types/Gist.ts` and export them as interfaces/types from the same. 

Not sure if we should move the query type to `src/composables/github/types/Gist.ts`  or into `src/composables/github/queries/user-gists.query.ts` . What do you think @WillHutt ?

2022-05-03 19:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/composables/github/useGists.ts
> +    data?: GistItem;
Please fix types:
```ts
data: Readonly<Ref<Readonly<[] | GistItem[]>>>
```

2022-05-03 19:32 UTC, AllanJeremy commented on vue3-ts-quasar/src/composables/github/useGists.ts
> +  const getUserGists = (): any => {
Prefer strongly typing whenever possible. I believe we should avoid the use of `any` whenever possible.

Remove the `any` once the return types in the `UseGists` interface have been correctly set.

2022-06-03 12:46 UTC, hdJerry commented on vue3-ts-quasar/src/composables/github/useGists.ts
> +    console.log(gists);
You can remove the console log

2022-06-03 16:24 UTC, merged