Vue3 apollo quasar/feat/single repo issues tab view
thisdot/starter.dev-github-showcases pull request #579
Opened 2022-09-02 13:29 UTC by hdJerry

2022-09-07 09:53 UTC, hdJerry commented
This is a merge of other PR's as some contents from them were needed, so when those PR's are closed this will be less bulky

2022-09-07 12:34 UTC, AllanJeremy requested changes

2022-09-07 12:34 UTC, AllanJeremy commented on vue3-apollo-quasar/src/views/Repository/RepositoryDetails.vue
> +          :dirpath="dirpath"
below you have something similar `repo-dir-path` but above it's one word, `dirpath`. Consistency is key. 

Could we pick one format? I'd suggest `dirPath` which would resolve to `dir-path` when accessing the prop.

2022-09-07 12:34 UTC, AllanJeremy commented on vue3-apollo-quasar/src/views/Repository/RepositoryDetails.vue
>        :repoName="repo"
Another thing, in some places you use props with `camelCase` and in others with `kebab-case`. The common convention in vue is to use `kebab-case`. Could you rename all `camelCase` usages to `kebab-case`?

2022-09-10 08:05 UTC, AllanJeremy approved these changes

2022-09-12 09:42 UTC, merged