chore: updated repository card to fit ticket criterias
thisdot/starter.dev-github-showcases pull request #647
Opened 2022-09-22 12:55 UTC by temitopeadesoji

Closes #631

2022-09-23 23:36 UTC, jesus4497 requested changes
LGTM! just a small change

2022-09-23 23:36 UTC, jesus4497 commented on nuxt-pinia-tailwind/plugins/formatter.ts
> +      return formatDistance(date, dateToCompare, options);
nit: I think we could reduce this to just one condition to make it easier to read
```suggestion
      if (!isValidDate(date) || !isValidDate(dateToCompare)) {
        return ''
      }
      const dateToFormat = typeof date === 'string' ? date : new Date(date)
      return formatDistance(date, dateToCompare, options); 
      
```

2022-09-30 10:47 UTC, hdJerry approved these changes
LGTM

2022-09-30 16:45 UTC, jesus4497 requested changes
Just a small change! We should also add tests for this components

2022-09-30 16:45 UTC, jesus4497 commented on nuxt-pinia-tailwind/components/RepositoryCard/RepositoryCard.vue
> +      default: () => {},
This is actually returning `void` not an actual object.
```suggestion
      default: () => ({
       language: '',
       updatedAt: new Date(),
       forkCount: 0,
       stargazerCount: 0
      }),
```

2023-08-04 10:41 UTC, hdJerry approved these changes

2023-08-04 10:41 UTC, merged