chore: repo card with story and test
thisdot/starter.dev-github-showcases pull request #737
Opened 2022-10-27 16:34 UTC by hdJerry

# Create repository card

## Background

This will be a reusable component that displays details about a repository. On the home page and profile page, a user will see a list of their repositories. This component is intended to be the building block for that - a single card for a repository, showing pertinent data about that repo.

## Acceptance

- [x] Card view for use on repository lists
- [x] should always have:
    - [x] repo name
    - [x] visibility tag (public / private)
    - [x] description (if available)
    - [x] main language with color dot
    - [x] star icon with number of stars on repo
    - [x] last updated text
    - [x] optional - star button on right to add a star to the repo (does not need to function yet)

## Notes

![Screenshot 2022-10-27 at 17 33 57](https://user-images.githubusercontent.com/28502531/198347989-71abd724-a85d-4e2b-a093-5fef37ac0d67.jpg)

2022-10-28 12:35 UTC, mbicknese requested changes

2022-10-28 12:35 UTC, mbicknese commented on solidjs-tailwind/src/components/RepoCard/RepoCard.stories.jsx
> +Default.args = {
Can't we use the `data.js` file for this?

2022-10-28 13:30 UTC, kodejuice commented on solidjs-tailwind/pnpm-lock.yaml
> +  dayjs: ^1.11.6
lighter than moment.js i guess

2022-10-28 17:18 UTC, hdJerry commented on solidjs-tailwind/pnpm-lock.yaml
> +  dayjs: ^1.11.6
Because that's what I have used before.

2022-10-28 17:19 UTC, hdJerry commented on solidjs-tailwind/src/components/RepoCard/RepoCard.stories.jsx
> +  <Router>
the error was for us to wrap in a Router. Not sure what you mean, though. Maybe a code snippet

2022-11-04 14:05 UTC, vyktoremario commented on solidjs-tailwind/pnpm-lock.yaml
> +  dayjs: ^1.11.6
What about `date-fns`?

2022-11-11 09:26 UTC, vyktoremario submitted a review, later dismissed

2022-11-11 09:29 UTC, vyktoremario approved these changes

2022-11-11 09:34 UTC, merged