feat(solidjs-tailwind): Adds RepoHeading Component
thisdot/starter.dev-github-showcases pull request #982
Opened 2022-11-28 20:59 UTC by danecando

This PR ports over the RepoHeading component for use in the solid showcase

### Changes
- Adds RepoHeading component
- Adds PrivacyIcon component
- Adds RepoHeading css module
- Adds RepoHeading story

Closes #935

2022-11-29 08:08 UTC, vyktoremario submitted a review, later dismissed

2022-11-29 09:06 UTC, hdJerry requested changes

2022-11-29 09:06 UTC, hdJerry commented on solidjs-tailwind/src/components/RepoHeading/RepoHeading.stories.tsx
> +Public.args = {
It would be nice if we could find a way to make this object re-useable as just one value differs from the other

2022-11-30 08:51 UTC, hdJerry approved these changes

2022-11-30 08:52 UTC, vyktoremario approved these changes

2022-11-30 15:57 UTC, merged